backend/novalinga/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/health', to: 'health#health'
  
  resources :courses, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :lessons, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :phrases, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end
  end
  
  resources :userscourses, only: [:create, :destroy],param: :course_id
  resources :phonetics, only: [:index, :show]
  # Routes for Google authentication
  # [START login]
  # get "/login", to: redirect("/auth/google_oauth2")
  # [END login]

  # [START sessions]
  # get "/auth/google_oauth2/callback", to: "sessions#create"

  # resource :session, only: [:create, :destroy]
  # [END sessions]

  # [START logout]
  #get "/logout", to: "sessions#destroy"
  # [END logout]
  root 'courses#index'
  delete "/logout", to: "sessions#logout"
  get "/get_user", to: "sessions#get_user"
  get "/redirect", to: "sessions#redirect"
  get "/fresh-token/:uid", to: "sessions#fresh_token"
  resources :sessions, only: :index
  get "/auth/:provider/callback" => 'sessions#create'
end

backend/novalinga/app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  validates :title, presence: true
  validates :image_url, presence: true
  validates :course_id, presence: true

  has_many :phrases, dependent: :destroy
end

backend/novalinga/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    include ApplicationHelper
    include LessonsHelper
    before_action :require_login, only: [:index, :show], :unless => :html_request?
    before_action :set_course, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    before_action :set_lesson, only: [:show, :edit, :update,:destroy]
    # GET /lessons
    def index
        @lessons = Lesson.where(course_id: @course[:id])
        if @lessons
            respond_to do |format|
              format.json { render json: @course.errors, status: :unprocessable_entity }
                format.html  { render :index }
            end
        else
            respond_to do |format|
                format.json { render json: @lessons.errors, status: :unprocessable_entity }
                format.html  { redirect_to courses_path, flash: {danger: "Please select a course."} }
            end
        end
    end

    # GET course/:course_id/lessons/:id
    def show
        respond_to do |format|
            format.json { render json: {message: "Lesson retrieved with id: #{params[:id]}", data: @lesson}, status: :ok}
            format.html { render :show} 
        end
    end

    def edit
    end

    def new
        @lesson = Lesson.new
    end

    # #POST /courses/:id/lessons
    def create 
        @lesson = Lesson.new(lesson_params)
        respond_to do |format|
            if @lesson.save
              format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully created.' }
              format.json { render json: @lesson, status: :created }
            else
              format.html { render :new }
              format.json { render json: @course.errors, status: :unprocessable_entity }
            end
          end
    end


    # #POST /lessons
    # def create 
    #     @lesson = Lesson.new(lesson_params)
    #     @lesson.save
    #     render json: @lesson, status: :created
    # end

    def update
        respond_to do |format|
            if @lesson.update(lesson_params)
                format.html { redirect_to course_lesson_path(@course, @lesson), flash: {info: 'Lesson was successfully updated.'} }
                format.json { render json: {message: "Lesson Updated with id: #{@lesson[:id]}", data: @lesson}, status: :ok }
            else
                format.html { render :edit }
                format.json { render json: @course.errors, status: :unprocessable_entity }
            end
        end
    end

    #DELETE /courses/:course_id/lessons/:id
    def destroy
        respond_to do |format|
            if @lesson.destroy
                format.html { redirect_to course_lessons_path(@course), flash: {info: 'Lesson was successfully deleted.'} }
                format.json { render json: {message: "Lesson Deleted with id: #{@lesson[:id]}"}, status: :ok }
            else
                format.html { render :index }
                format.json { render json: @lesson.errors, status: :unprocessable_entity }
            end
        end
        
    end

    # #DELETE /lessons/:id
    # def destroy
    #     @lesson = Lesson.find(params[:id])
    #     @lesson.destroy
    #     render json: @lesson, status: :ok
    # end

    private
    def lesson_params
        params.require(:lesson).permit(:title, :image_url, :course_id)
    end
end

backend/novalinga/app/helpers/lessons_helper.rb
module LessonsHelper
    # Use callbacks to share common setup or constraints between actions.
    def set_course
        @course = Course.find(params[:course_id])
    end

    def set_lesson
        @lesson = Lesson.find(params[:id])
    end
end

backend/novalinga/app/views/lessons/_form.html.erb
<%= form_with(model: @lesson, url: course_lesson_path(@course, @lesson), local: true) do |form| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this booking from being saved:</h2>
      <ul>
        <% @lesson.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/novalinga/app/views/lessons/_new_form.html.erb
<%= form_with(model: @lesson, url: course_lessons_path(@course), local: true) do |form| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this booking from being saved:</h2>
      <ul>
        <% @lesson.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

    <%= hidden_field :lesson, :course_id, :value => @course.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/novalinga/app/views/lessons/index.html.erb
<h1>Lessons for Course: <%= @course.title%></h1>
<table>
  <thead>
    <tr>
      <td>id</td>
      <td>Title</td>
      <td>image_url</td>
      <td>course title</td>
      <td>created_at</td>
      <td>updated_at</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson[:id] %></td>
        <td><%= lesson[:title] %></td>
        <td><%= lesson[:image_url] %></td>
        <td><%= @course[:title] %></td>
        <td><%= lesson[:created_at].strftime('%F') %></td>
        <td><%= lesson[:updated_at].strftime('%F') %></td>
        <td><%= link_to 'Phrases', course_lesson_phrases_path(@course, lesson) %></td>
        <td><%= link_to 'Show', course_lesson_path(@course, lesson) %></td>
        <td><%= link_to 'Edit', edit_course_lesson_path(@course, lesson) %></td>
        <td><%= button_to 'Destroy', course_lesson_path(@course, lesson), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Go to courses', courses_path %>

<%= link_to 'New Lesson', new_course_lesson_path %>

backend/novalinga/app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'new_form', course: @course %>

<%= link_to 'Back', courses_path %>

backend/novalinga/app/views/lessons/show.html.erb
<table>
  <thead>
    <tr>
      <td>id</td>
      <td>Title</td>
      <td>image_url</td>
      <td>course title</td>
      <td>created_at</td>
      <td>updated_at</td>
    </tr>
  </thead>
  <tr>
    <td><%= @lesson[:id] %></td>
    <td><%= @lesson[:title] %></td>
    <td><%= @lesson[:image_url] %></td>
    <td><%= @course[:title] %></td>
    <td><%= @lesson[:created_at].strftime('%F') %></td>
    <td><%= @lesson[:updated_at].strftime('%F') %></td>
  </tr>
</table>
<%= link_to 'Edit', edit_course_lesson_path(@course, @lesson) %> |
<%= link_to 'Back', course_lessons_path %>