backend/novalinga/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/health', to: 'health#health'
  
  resources :courses, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :lessons, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :phrases, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end
  end
  
  resources :userscourses, only: [:create, :destroy],param: :course_id
  resources :phonetics, only: [:index, :show]
  # Routes for Google authentication
  # [START login]
  # get "/login", to: redirect("/auth/google_oauth2")
  # [END login]

  # [START sessions]
  # get "/auth/google_oauth2/callback", to: "sessions#create"

  # resource :session, only: [:create, :destroy]
  # [END sessions]

  # [START logout]
  #get "/logout", to: "sessions#destroy"
  # [END logout]
  root 'courses#index'
  delete "/logout", to: "sessions#logout"
  get "/get_user", to: "sessions#get_user"
  get "/redirect", to: "sessions#redirect"
  get "/fresh-token/:uid", to: "sessions#fresh_token"
  resources :sessions, only: :index
  get "/auth/:provider/callback" => 'sessions#create'
end

backend/novalinga/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    include ApplicationHelper
    include CoursesHelper
    before_action :require_login, only: [:index, :show], :unless => :html_request?
    before_action :set_course, only: [:show, :edit, :update, :destroy], :if => :html_request?
    # GET /courses
    def index
        @courses = Course.all
        respond_to do |format|
            format.json { render json: {message: "Courses retrieved", data: @courses}, status: :ok }
            format.html  { render :index}
        end
    end

    # GET /courses/:id
    def show
        respond_to do |format|
            format.json { render json: {message: "Course retrieved with id: #{params[:id]}", data: @course}, status: :ok }
            format.html { render :show} 
        end
    end

    def new
        @course = Course.new
    end

    def edit
        
    end

    # #POST /courses
    def create 
        @course = Course.new(course_params)
        respond_to do |format|
            if @course.save
              format.html { redirect_to @course, notice: 'Course was successfully created.' }
              format.json { render json: @course, status: :created }
            else
              format.html { render :new }
              format.json { render json: @course.errors, status: :unprocessable_entity }
            end
          end
    end

    # # PUT /courses/:id
    def update
        respond_to do |format|
            if @course.update(course_params)
                format.html { redirect_to @course, flash: {info: 'Course was successfully updated.'} }
                format.json { render json: {message: "Course Updated with id: #{@course[:id]}", data: @course}, status: :ok }
            else
                format.html { render :edit }
                format.json { render json: @course.errors, status: :unprocessable_entity }
            end
        end
    end

    # #DELETE /courses/:id
    def destroy
        respond_to do |format|
            if @course.destroy
                format.html { redirect_to courses_path, flash: {info: 'Course was successfully deleted.'} }
                format.json { render json: {message: "Course Deleted with id: #{@course[:id]}"}, status: :ok }
            else
                format.html { render :index }
                format.json { render json: @course.errors, status: :unprocessable_entity }
            end
        end
        
    end

    private
    def course_params
        params.require(:course).permit(:title, :image_url, :input_language, :output_language)
    end
end

backend/novalinga/app/helpers/courses_helper.rb
module CoursesHelper
    # Use callbacks to share common setup or constraints between actions.
    def set_course
        @course = Course.find(params[:id])
    end
end

backend/novalinga/app/views/courses/_form.html.erb
<%= form_with(model: @course, local: true) do |form| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this booking from being saved:</h2>
      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :input_language %>
    <%= form.text_field :input_language %>
  </div>

  <div class="field">
    <%= form.label :output_language %>
    <%= form.text_field :output_language %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/novalinga/app/views/courses/edit.html.erb
<h1>Editing Course <%= @course.id%></h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

backend/novalinga/app/views/courses/index.html.erb
<h1>Courses</h1>
<table>
  <thead>
    <tr>
      <td>id</td>
      <td>Title</td>
      <td>image_url</td>
      <td>input_language</td>
      <td>output_language</td>
      <td>created_at</td>
      <td>updated_at</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <% course.attributes.each do |attribute| %>
          <td><%= attribute[1] %></td>
        <% end %>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Lessons', course_lessons_path(course) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Course', new_course_path %>

backend/novalinga/app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

backend/novalinga/app/views/courses/show.html.erb
<table>
  <thead>
     <tr>
        <td>id</td>
        <td>Title</td>
        <td>image_url</td>
        <td>input_language</td>
        <td>output_language</td>
        <td>created_at</td>
        <td>updated_at</td>	 	 	 	
      </tr>
</thead>  
<tr>
        <% @course.attributes.each do |attribute| %>
          <td><%= attribute[1] %></td>
        <% end %> </tr>
    </table>
<%= link_to 'Lessons', course_lessons_path(@course) %> |
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>